server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://43.138.34.94:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true



